name: "HCL AppScan DAST - ephemeral presence"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ASoC DAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.5
        
        with:
          baseurl:  https://cloud.appscan.com/eu
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{vars.ASOC_APPID}}
          scan_type: 'staging'
          dynamic_scan_type: upload
          scan_or_scant_file: 'altoro_fast.scant'
          ephemeral_presence: true
      - uses: actions/upload-artifact@v3
        name: Upload HCL AppScan HTML Report to Github Artifacts
        with:
          name: AppScan Security Scan HTML Report 
          path: '**/AppScan*.html'
        if: success() || failure()
